[build]
  command = "pip install -r requirements_build.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.7"

[[redirects]]
  from = "/*"
  to = "/staticfiles/:splat"
  status = 200

[context.production.environment]
  DEBUG = "0"
  DJANGO_SETTINGS_MODULE = "portfolio.settings"
  ALLOWED_HOSTS = ".netlify.app"
  PYTHONPATH = "."
