[build]
  base = "."
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/wsgi/:splat"
  status = 200
  force = true

[functions]
  external_node_modules = ["@netlify/functions"]
  directory = "netlify/functions"
