# render.yaml
services:
  - type: web
    name: core
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT
